### PR TITLE
SumatraPdf support for forward and inverse search.

### PR DESCRIPTION
**Pull request by dietercastel**
I made a slight modification to compiler.vim to support SumatraPdf forward search which I sometimes use on Windows.
I also included a README to help people set this up but it is debatable whether this README should be included in your project.
I hope you find this a useful (small) addition to your extensive project.

### CODE REVIEW

**Comment by tyll** [comment]
Thank you. Adding a new README is not a good approach  here, since there is already a lot of documentation that is created from XML files. Can you please look through https://github.com/vim-latex/vim-latex/blob/master/doc/latex-suite.xml and see which of your instructions need to be integrated there? Forward/Inverse search is already covered there.

**Comment by dietercastel** [comment]
I will look into merging the README info into the the xml you mentioned and adapt the pull request accordingly.

**Comment by dietercastel** [comment]
I removed the README and updated the documentation xml. I also thought it would be a good idea to enable the synctex flag by default for pdfLaTeX. So I did and also mentioned it in the documentation.

**Comment by tyll** [comment]
thank you

**Pull request merged**
