### PR TITLE
Improved folding feature

### PR DESCRIPTION
**Pull request by gerw**
This pull request should improve the folding feature of latex-suite:
- Improved(?) the foldtext
- Itemize environments can nest
- Replaced a stack implementation by vim lists
- Add some debugging code to SyntaxFolds.vim
- Removed some bugs
- Speedup of folding

Please test, whether this works for you. Let me know, if you find some bugs or some weird behaviour for your documents.

### CODE REVIEW

**Comment by lucc** [comment]
I am using this now. I did not see any problems yet but it seems to me that I can also see nested itemize envs being folded when i'm on master. Maybe this is due to my vimrc, no idea.

**Comment by gerw** [comment]
Thank you for your reply. If I am use something like
```latex
\begin{itemize}
	\item a

	\item b
		\begin{itemize}
			\item c

			\item d

			\item e

		\end{itemize}

	\item f

\end{itemize}
```
on master, all `\items` and the outer `itemize` are folded correctly, but the inner `itemize` is not folded at all. Note that you have to use
```vim
let g:Tex_FoldedEnvironments = 'itemize'
```
(preferably in `ftplugin/tex.vim`) in order to fold the `itemize` environment, the default value is
```vim
'verbatim,comment,eq,gather,align,figure,table,thebibliography,keywords,abstract,titlepage'
```
Could you post your folding-related settings?

**Comment by lucc** [comment]
Ok I tested with your itemize example in a otherwise empty file like this:
```sh
vim -u NORC --cmd "set rtp+=path/to/vim-latex" --cmd "let g:Tex_FoldedEnvironments = 'itemize'" test.tex
```
and can see the difference between master and this branch. The folding is indeed better but for me the outer itemize is only folded if I surround it with a document env.

I did not have `itemize` in my `Tex_FoldedEnvironments` (maybe because I did not like the old behavior). This is the latex-suite setup in my vimrc:
```vim
"Plugin 'LaTeX-Help' " is included in vim-latex
let g:ngerman_package_file = 1
let g:Tex_Menus = 0
"let g:Tex_UseUtfMenus = 1

" The other settings for vim-latex are in the LucLatexSuiteSettings
" autocmdgroup.
if has('mac') | let g:Tex_ViewRule_pdf = 'open -a Preview' | endif
let g:Tex_UseMakefile = 1
let g:Tex_CompileRule_pdf = 'latexmk -silent -pv -pdf $*'
let g:Tex_DefaultTargetFormat = 'pdf'
let g:Tex_SmartQuoteOpen = '„'
let g:Tex_SmartQuoteClose = '“'
" the variable Tex_FoldedEnvironments holds the beginnings of names of
" environments which should be folded.  The innermost environments should come
" first.
let s:TexFoldEnv = [ 'verbatim',
	           \ 'comment',
	           \ 'eq',
	           \ 'gather',
	           \ 'align',
	           \ 'figure',
	           \ 'table',
		   \ 'luc',
		   \ 'dogma',
	           \ ]
" environments for structure of mathematical texts (they can contain other
" stuff)
call extend(s:TexFoldEnv, [ 'th',
			  \ 'satz',
			  \ 'def',
			  \ 'lem',
			  \ 'rem',
			  \ 'bem',
			  \ 'proof',
			  \ ])
" quotes can contain other stuff
call extend(s:TexFoldEnv, ['quot',])
" the beamer class has two top level environments
call extend(s:TexFoldEnv, [ 'block',
			  \ 'frame',
			  \])
" environments for the general document
call extend(s:TexFoldEnv, [ 'thebibliography',
			  \ 'keywords',
			  \ 'abstract',
			  \ 'titlepage',
			  \ ])
let g:Tex_FoldedEnvironments = join(s:TexFoldEnv, ',')
let s:TexFoldSec = [
      \ 'part',
      \ 'chapter',
      \ 'section',
      \ 'subsection',
      \ 'subsubsection',
      \ 'paragraph',
      \ 'subparagraph',
      \ ]
let g:Tex_FoldedSections = join(s:TexFoldSec, ',')
```
It results in `Tex_FoldedEnvironments` being `verbatim,comment,eq,gather,align,figure,table,luc,dogma,th,satz,def,lem,rem,bem,proof,quot,block,frame,thebibliography,keywords,abstract,titlepage`.

**Comment by gerw** [comment]
Weird, for me, the outer itemize is also folded without a surrounding document environment.

I used
```sh
"gvim" -U NONE -u ~/.vim/vimrc_latex-suite  --cmd "let g:Tex_FoldedEnvironments = 'itemize' | set foldcolumn=6" test.tex
```
with `~/.vim/vimrc_latex-suite` being
```vim
let &rtp = substitute(&rtp, '\.vim\>', '.vim/bundle/vim-latex-suite', 'g')

filetype plugin on 
```
to get a basic configuration (beside some standard plugins, only latex-suite is loaded, without any user configuration).

Similarly, if I additionally load your configuration, with 
```vim
let g:Tex_FoldedEnvironments = join(s:TexFoldEnv + ['itemize'], ',')
```
also the outer itemize is folded without a surrounding document environment.




(I also do not fold itemizes)

**Pull request merged**
