### PR TITLE
Update bib_latexSuite.vim

### PR DESCRIPTION
**Pull request by thedoctar**
Fixes this issue: https://github.com/vim-latex/vim-latex/issues/192

### CODE REVIEW

**Comment by gerw** [comment]
Can you explain, why this is necessary? In my opinion, `imap.vim` should be loaded by default. (It is also not necessary in, e.g., tex_latexSuite.vim`).

**Comment by thedoctar** [comment]
Hi gerw, if I open a .bib file, it complains that IMAP is not loaded. By adding the line, the issue is fixed. I'm not sure why it's different for tex files. Maybe there is something more fundamental going on.

**Comment by gerw** [comment]
What happens if you open just vim? Is `imap.vim` loaded? (It should be loaded always.)

**Comment by thedoctar** [comment]
The problem only occurs when I open a bib file like `vim file.bib`.

**Comment by thedoctar** [comment]
Here are some possibly relevant lines of my `.vimrc` file:

```
autocmd BufWinEnter ~/Documents/* silent loadview
filetype plugin on
filetype indent on
filetype detect

" OPTIONAL: Starting with Vim 7, the filetype of empty .tex files defaults to
" 'plaintex' instead of 'tex', which results in vim-latex not being loaded.
" The following changes the default filetype back to 'tex':
let g:tex_flavor='latex'
```

**Comment by gerw** [comment]
No, this file should be loaded always. There is no explicit loading for tex-files either. Hence, it does not make sense that it is loaded for bib-files (as in this PR). Do you have any mention of `imaps.vim` in your config?

**Comment by thedoctar** [comment]
No. 

Here is the error when I do not load imaps.vim explicitly:
```
E117: Unknown function: IMAP
Error detected while processing /home/user/.vimrc[35]..BufRead Autocommands for "*.bib"..FileType Autocommands for "*"..function <SNR>8_LoadFTPlugin[17]..script /home/user/.vim/ftplugin/bib_latexSuite.vim[17]../home/user/.vim/ftplugin/latex-suite/main.vim[943]../home/user/.vim/ftplugin/latex-suite/envmacros.vim[270]..function <SNR>16_Tex_SectionMacros:
line    7:
```

This is only one example. I get multiple such errors.

**Comment by gerw** [comment]
Which version of vim are you using?

**Comment by thedoctar** [comment]
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Aug 11 2020 01:16:00)
Included patches: 1-1419
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            -gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              -perl              +title
-clientserver      +job               +persistent_undo   -toolbar
-clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         -python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       -lua               -ruby              +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             -sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -O2 -fno-strength-reduce -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim        -lm -ltinfo  -ldl           
```

**Comment by gerw** [comment]
Can you test another version of vim? Do you have any other plugins installed? Can you try an installation which uses only the latex suite?

**Comment by thedoctar** [comment]
Our university server has vim 8.1 and there doesn't seem to be a bug there. So I don't know what the problem is. I manually compiled vim 8.2 on my laptop.

**Pull request closed without merging**
