### PR TITLE
Map "`w" to "\omega" and "`o" to "\omicron"

### PR DESCRIPTION
**Pull request by huangzonghao**
* The setting in the main.vim that mapped `` `w `` to `\wedge` is commented
  out since we already have `` `&`` mapped for that. Having two keys mapping
  to the same thing while `\omega` has no key-mapping is a huge waste.

* Also added a new mapping that would expand `` `o`` to `\omicron`. While the
  letters may seem similar in use but this change helps to make the
  behavior of the plugin consistant with the description on the manual.
  Besides `` `o`` has no mapping before.

Quote from the Reference Manual

>  3.5 Greek Letter Mappings
> Lower case
>  `` `a`` through `` `z`` expand to `\alpha` through `\zeta`.

### CODE REVIEW

**Comment by gerw** [comment]
Are you sure that LaTeX has `\omicron`?

See https://tex.stackexchange.com/questions/233257/omicron-not-working-in-latex

**Comment by huangzonghao** [comment]
Well it depends on the tex distribution. And latex users may use [unicode-math](https://mirror.hmc.edu/ctan/macros/latex/contrib/unicode-math/unimath-symbols.pdf) to include `\omicron`.
But whichever way it shouldn't be an issues for us to expand `` ` `` + `[a - z]` to the corresponding greek letters. But I do think it's worth mentioning the availability of `\omicron` in the reference manual as well.

I will work on patch for that.

**Comment by huangzonghao** [comment]
Hey, I have worked out the patch per discussed in #123 . Please take a look.

I mainly discussed the availability issue of `\omicron` and advised users to make their choice in the documentation.

 But no matter what I do think we need to distinguish between `\omicron` and Latin `o` as they could completely mean different things in math or physics. Having the expansion would allow the users to distinguish the two letters while writing their document and easily manage the font of `\omicron` as they wish without being forced to go into their lengthy documents and manually switch particular latin `o`s to `\omicron`.

Since we don't have any use of `` `o`` at the moment, why not do the favor and give the choice to the users?

**Comment by gerw** [comment]
Thank you. Would it make sense to make also all upper Greek letters available? In the same spirit as for `\omicron`, they might not be defined, but the user may want to use it?

**Comment by huangzonghao** [comment]
Yes, I totally agree that we should expand the upper case letters as well. So the new patches are here. Please take a look.

**Pull request merged**
