### PR TITLE
Fix expansion of abbreviations in the middle of a line

### LINKED ISSUE #141: Expansion of abbreviation only works at the end of a line
To reproduce the problem, create an abbreviation, such as

```vim
:iab bd text
```

Then create a line with two tokens:

```
before after
```

Put the cursor under "after" and type `b`, `d`, `Space`. The abbreviation will fail to expand.

It seems the code is actually looking for the last word in the line, instead of where the current cursor position is... So in fact if you have a line with `before after bd` and inser anything to the middle of it, this will trigger the expansion of `text`.

(I have a fix ready, will send a PR your way shortly.)

Originally reported on [this question by Romas](https://vi.stackexchange.com/questions/17310/vim-latex-sometimes-abbreviations-do-not-expand-in-tex-buffers) at vim on StackExchange

### PR DESCRIPTION
**Pull request by filbranden**
Fixes #141

### CODE REVIEW

**Comment by filbranden** [comment]
This has a shortcoming in that it will expand the abbreviation even if it's not followed by a blank. For instance, in a line with `before after`, putting the cursor under "after" and typing `b`, `d`, `Esc` will produce `before textafter` which is probably not desirable, not really how abbreviations usually work... I'd be willing to revisit this to try to fix that too, let me know your thoughts.

**Comment by gerw** [comment]
I am wondering about your comment. If I have (without latex-suite) `before after`, and if I put the cursor on the `a´ and type `bd<esc>` I get `before textafter`. So this seems to be vim's standard behaviour.

**Comment by filbranden** [comment]
@gerw Yes, that's correct, I think I was not seeing this right away because there was a delay (shorter `timeoutlen` made this faster.) I added some traces to IMAP's LookupCharacter and I noticed when I press `<Esc>` it doesn't go through it, so I guess that's same as expected behavior.

So looks like this PR might be just enough... Unless you find other trouble with it that I didn't see.

Cheers,
Filipe

**Comment by gerw** [comment]
Thank you for the patch!

**Pull request merged**
